# Generated by Django 4.2.6 on 2023-11-13 13:00

from django.db import migrations, models
import django.db.models.deletion
import perinatal.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anticonceptivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HcpHcPerinatalManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HcpHcPerinatal',
            fields=[
                ('hcp_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hcp_personaid', models.CharField(blank=True, max_length=15, null=True)),
                ('hcp_nrodocumento_0019', models.CharField(blank=True, help_text='Nro de Documento', max_length=20, null=True)),
                ('hcp_telefono_0005', models.SmallIntegerField(blank=True, help_text='Teléfono', null=True)),
                ('hcp_fechanacimiento_0006', models.DateField(blank=True, help_text='Fecha de nacimiento', null=True, validators=[perinatal.validators.validacion_fecha_nacimiento])),
                ('hcp_edad_0009', models.SmallIntegerField(blank=True, help_text='Edad', null=True, validators=[perinatal.validators.validacion_rango_edad])),
                ('hcp_alertaedad_0010', models.BooleanField(blank=True)),
                ('hcp_alfabeta_0012', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Alfabeta', max_length=1)),
                ('hcp_estudios_0013', models.CharField(blank=True, choices=[('Ninguno', 'Ninguno'), ('Primario', 'Primario'), ('Secundario', 'Secundario'), ('Universitario', 'Universitario')], help_text='Estudios', max_length=40, null=True)),
                ('hcp_aniosmayornivel_0014', models.SmallIntegerField(blank=True, help_text='Años mayor nivel', null=True)),
                ('hcp_estadocivil_0015', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Estado civil', max_length=40, null=True)),
                ('hcp_vivesola_0016', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Vive Sola', max_length=1, null=True)),
                ('hcp_establecimientocontrolid_0017', models.CharField(blank=True, help_text='Lugar de Control Prenatal', max_length=40, null=True)),
                ('hcp_establecimientopartoid_0018', models.CharField(blank=True, help_text='Lugar del Parto', max_length=40, null=True)),
                ('hcp_ant_tbcfamiliar_0020', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='TBC Familiar', max_length=1, null=True)),
                ('hcp_ant_tbcpersonal_0021', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='TBC Personal', max_length=1, null=True)),
                ('hcp_ant_diabetfamiliar_0022', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Diabetes Familiar', max_length=1, null=True)),
                ('hcp_ant_diabetpersonal_0023', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Diabetes Personal', max_length=1, null=True)),
                ('hcp_ant_hipertenfamiliar_0024', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Hipertensión Familiar', max_length=1, null=True)),
                ('hcp_ant_hipertenpersonal_0025', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Hipertensión Personal', max_length=1, null=True)),
                ('hcp_ant_preeclampsiafamiliar_0026', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Preeclampsia Familiar', max_length=1, null=True)),
                ('hcp_ant_preeclampsiapersonal_0027', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Preeclampsia Personal', max_length=1, null=True)),
                ('hcp_ant_eclampsiafamiliar_0028', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Eclampsia Familiar', max_length=1, null=True)),
                ('hcp_ant_eclampsiapersonal_0029', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Eclampsia Personal', max_length=1, null=True)),
                ('hcp_ant_otracondmedicafamiliar_0030', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Otras Cond. Medicas Familiar', max_length=1, null=True)),
                ('hcp_ant_otracondmedicapersonal_0031', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Otras Cond. Medicas Personal', max_length=1, null=True)),
                ('hcp_ant_cgiagenitourinaria_0032', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Cgia genito-urinaria', max_length=1, null=True)),
                ('hcp_ant_infertilidad_0033', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Infertilidad', max_length=1, null=True)),
                ('hcp_ant_nefropatia_0035', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Cardiopatía', max_length=1, null=True)),
                ('hcp_ant_cardiopat_0034', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Nefropatia', max_length=1, null=True)),
                ('hcp_ant_violencia_0036', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Violencia', max_length=1, null=True)),
                ('hcp_ant_vih_0432', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='VIH+', max_length=1, null=True)),
                ('hcp_ant_ultimoprevio_0038', models.CharField(blank=True, choices=[('n/c', 'n/c'), ('<2500g', '<2500g'), ('normal', 'normal'), ('>=4000g', '>=4000g')], help_text='Ultimo Previo', max_length=40, null=True)),
                ('hcp_ant_antecedentegemelar_0039', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Antecedente Gemelar', max_length=1, null=True)),
                ('hcp_ant_gestasprevia_0040', models.SmallIntegerField(blank=True, help_text='Cantidad Gestas Previas', null=True)),
                ('hcp_ant_abortos_0041', models.SmallIntegerField(blank=True, help_text='Cantidad de Abortos', null=True)),
                ('hcp_ant_partvaginales_0042', models.SmallIntegerField(blank=True, help_text='Cantidad de Partos Vaginales', null=True)),
                ('hcp_ant_nacidovivo_0043', models.SmallIntegerField(blank=True, help_text='Cant. de Nacidos Vivos ', null=True)),
                ('hcp_ant_viven_0044', models.SmallIntegerField(blank=True, help_text='Cantidad de hijos que viven', null=True)),
                ('hcp_ant_tresabortosconsecu_0045', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='3 Abortos consecutivos', max_length=1, null=True)),
                ('hcp_ant_cesareas_0047', models.SmallIntegerField(blank=True, help_text='Cantidad de Césareas', null=True)),
                ('hcp_ant_embectopico_0409', models.SmallIntegerField(blank=True, help_text='Cantidad Embarazo Ectópico', null=True)),
                ('hcp_ant_partosprevios_0046', models.SmallIntegerField(blank=True, help_text='Cantidad Partos Previos', null=True)),
                ('hcp_ant_nacidomuerto_0048', models.SmallIntegerField(blank=True, help_text='Cantidad Nacidos Muertos', null=True)),
                ('hcp_ant_muertoantessemana_0049', models.SmallIntegerField(blank=True, help_text='Cant. de Muertos Primera Semana', null=True)),
                ('hcp_ant_muertodespsemana_0050', models.SmallIntegerField(blank=True, help_text='Cant. de Muertos Desp. de la Primera Semana.', null=True)),
                ('hcp_ant_fechaembarazoanterior_0051', models.DateField(blank=True, help_text='Fecha de Fin Embarazo Anterior', null=True)),
                ('hcp_ant_finmenosdeunanio_0052', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Menor a 1 año', max_length=1, null=True)),
                ('hcp_ant_embarazoplaneado_0053', models.CharField(blank=True, choices=[('S', 'Si'), ('N', 'No')], help_text='Embarazo Planeado', max_length=1, null=True)),
                ('hcp_ant_fracasoanticonceptivoid_0054', models.SmallIntegerField(blank=True, help_text='Fracaso Anticonceptivo', null=True)),
                ('hcp_fechadeapertura', models.DateTimeField(blank=True, null=True)),
                ('hcp_idusuarioapertura', models.CharField(blank=True, max_length=40, null=True)),
                ('hcp_fechacierre', models.DateTimeField(blank=True, null=True)),
                ('hcp_idusuariocierre', models.CharField(blank=True, max_length=40, null=True)),
                ('hcp_usuariobaja', models.CharField(blank=True, max_length=40, null=True)),
                ('hcp_fechabaja', models.DateTimeField(blank=True, null=True)),
                ('hcp_motivobaja', models.CharField(blank=True, max_length=60, null=True)),
                ('hcp_aperturaestableid', models.CharField(blank=True, max_length=40, null=True)),
                ('hcp_bajaestableid', models.CharField(blank=True, max_length=40, null=True)),
                ('hcp_cierraestableid', models.CharField(blank=True, max_length=40, null=True)),
                ('hcp_fechamodificacion', models.DateTimeField(blank=True, null=True)),
                ('hcp_usuariomodificacion', models.CharField(blank=True, max_length=40, null=True)),
                ('anticonceptivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='perinatal.anticonceptivos')),
                ('hcp_etnia_0011', models.ForeignKey(blank=True, help_text='Etnia', null=True, on_delete=django.db.models.deletion.CASCADE, to='perinatal.etnia')),
            ],
            options={
                'db_table': 'hcp_hcperinatalsti',
            },
        ),
    ]
